modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/OverFluxStudios/NetherEnhanced/projects/1"
[[mods]]
modId="netherenhanced"
version="DEV v1.3"
displayName="NetherEnhanced"
logoFile="examplemod.png"
credits="OverFlux Studios - Mod Development, @phat@ - Textures, LOLCAT Translation and Moral Support"
authors="OverFlux Studios, @phat@"
description='''
A simple mod that adds different things based around the nether!

This is WIP!
'''
[[dependencies.netherenhanced]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.netherenhanced]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
